services:
    Zikula\Module\CoreManagerModule\Form\Type\BasicInformationType:
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
          - '@zikula_core_manager_module.helper.progress_data_storage_helper'
        tags: [form.type]

    Zikula\Module\CoreManagerModule\Form\Type\BranchSelectionType:
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
          - '@zikula_core_manager_module.helper.progress_data_storage_helper'
        tags: [form.type]

    Zikula\Module\CoreManagerModule\Form\Type\CommitType:
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
          - '@zikula_core_manager_module.helper.progress_data_storage_helper'
        tags: [form.type]

    Zikula\Module\CoreManagerModule\Form\Type\CoreVersionType:
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
        tags: [form.type]

    Zikula\Module\CoreManagerModule\Form\Type\ExecuteType:
        arguments:
          - '@translator.default'
        tags: [form.type]

    Zikula\Module\CoreManagerModule\Form\Type\JenkinsBuildType:
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.releasemanager'
          - '@zikula_core_manager_module.helper.progress_data_storage_helper'
        tags: [form.type]

    Zikula\Module\CoreManagerModule\Form\Type\ConfigType:
        arguments:
          - '@translator.default'
          - '@router'
        tags: [form.type]
