services:
    Zikula\Module\CoreManagerModule\Form\Type\BasicInformationType:
        class: Zikula\Module\CoreManagerModule\Form\Type\BasicInformationType
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
          - '@zikula_core_manager_module.progress_data_storage_helper'
        tags:
            - { name: 'form.type' }

    Zikula\Module\CoreManagerModule\Form\Type\BranchSelectionType:
        class: Zikula\Module\CoreManagerModule\Form\Type\BranchSelectionType
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
          - '@zikula_core_manager_module.progress_data_storage_helper'
        tags:
            - { name: 'form.type' }

    Zikula\Module\CoreManagerModule\Form\Type\CommitType:
        class: Zikula\Module\CoreManagerModule\Form\Type\CommitType
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
          - '@zikula_core_manager_module.progress_data_storage_helper'
        tags:
            - { name: 'form.type' }

    Zikula\Module\CoreManagerModule\Form\Type\CoreVersionType:
        class: Zikula\Module\CoreManagerModule\Form\Type\CoreVersionType
        arguments:
          - '@translator.default'
          - '@zikula_core_manager_module.github_api_wrapper'
        tags:
            - { name: 'form.type' }

    Zikula\Module\CoreManagerModule\Form\Type\ExecuteType:
        class: Zikula\Module\CoreManagerModule\Form\Type\ExecuteType
        arguments:
          - '@translator.default'
        tags:
            - { name: 'form.type' }

    Zikula\Module\CoreManagerModule\Form\Type\ConfigType:
        class: Zikula\Module\CoreManagerModule\Form\Type\ConfigType
        arguments:
          - '@translator.default'
          - '@router'
        tags:
            - { name: 'form.type' }
