stages:
    coreVersion:
        # - choose version from available versions (will imply prerelease or not)
        class: Zikula\Module\CoreManagerModule\Stage\CoreVersionStage
        order: 1
        default: true
    branchSelection:
        # - choose branch (defaults to the branch of the previous release)
        class: Zikula\Module\CoreManagerModule\Stage\BranchSelectionStage
        order: 2
    commit:
        # - select one of the latest X commits of the specified branch
        class: Zikula\Module\CoreManagerModule\Stage\CommitStage
        order: 3
    basicInformation:
        # - release title
        # - release announcement
        # - artifacts download URL
        class: Zikula\Module\CoreManagerModule\Stage\BasicInformationStage
        order: 4
    execute:
        # - create QA issue
        # - create release
        # - copy assets to GitHub
        # - If not prerelease do optionally:
        #   - If it is a new minor version
        #     - create new changelog file
        #     - create new upgrading file
        # - trigger CoreManager hooks
        class: Zikula\Module\CoreManagerModule\Stage\ExecuteStage
        order: 5
    complete:
        class: Zikula\Module\CoreManagerModule\Stage\CompleteStage
        order: 6
